// Generated by CoffeeScript 1.3.3
var AIOUploader;

AIOUploader = (function() {

  AIOUploader.token = '';

  AIOUploader.prototype.currentShortcut = '';

  function AIOUploader(selector, callback) {
    var _this = this;
    this.selector = selector;
    this.callback = callback;
    this.uploader = new AjaxUpload($(this.selector)[0], {
      action: "http://chute.com:3000/v1/upload?shortcut=" + this.currentShortcut + "&authorization=" + AIOUploader.token,
      name: 'avatar',
      allowedExtensions: ['jpg', 'jpeg', 'png', 'gif'],
      onSubmit: function() {
        _this.currentShortcut = _this.shortcut();
        return _this.uploader._settings.action = "http://chute.com:3000/v1/upload?shortcut=" + _this.currentShortcut + "&authorization=" + AIOUploader.token;
      },
      onComplete: function() {
        return _this.callback(false, "http://chute.com:3000/" + _this.currentShortcut);
      }
    });
  }

  AIOUploader.prototype.shortcut = function() {
    var possible, value;
    value = 'u';
    possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    while (true) {
      if (value.length === 10) {
        break;
      }
      value += possible.charAt(Math.floor(Math.random() * possible.length));
    }
    return value;
  };

  return AIOUploader;

})();
